# Generated by Django 4.0.2 on 2022-03-08 16:15

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='None Event', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='img',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
